### ISSUE TITLE
doesn't work in production environment if no_script_name is true

### ISSUE THREAD

**Issue by nibsirahsieu** [heristop/sf-combine-plugin#1]
Hi..
thanks for made this plugin compatible with propel 1.5.
I found an issue in the prod environment if i set no_script_name to true. It gives me 404 error. The requested URL /css-min/key/95558ffc86076c12137c00f48350acc0e2bc3b0c/t/1296051916.css was not found on this server.

**Comment by kevindew** [comment]
hello, no_script_name shouldn't be causing a problem as i run it in all my environments with that set to true. any chance you can turn on no_script_name in dev env, or debug mode in your prod env to get a message/stack trace of when the error is occurring?

**Comment by nibsirahsieu** [comment]
thanks.., i tried to debug in the prod environment.
1. adding error_reporting:   <?php echo (E_ALL | E_STRICT)."\n" ?> to the settings.yml
2. changing the 'err' level to 'debug' in the factories.yml
3. in index.php i changed the 3rd parameter to true
but the 'css' or 'js' actions is never executed. Firebug always gives me 404 not found error. If i try to open in the new window, for example : http://myblog.localhost/css-min/key/95558ffc86076c12137c00f48350acc0e2bc3b0c/t/1296238009.css, it always produce an error like mentioned in the first issue, except if i remove the 'css' or 'js' (http://myblog.localhost/css-min/key/95558ffc86076c12137c00f48350acc0e2bc3b0c/t/1296238009) extension it works.
PS: i'm using symfony 1.4

**Comment by nibsirahsieu** [comment]
my prod configurations
settings.yml
    .settings:
      no_script_name:         true
      logging_enabled:        true
      cache:                  true
      error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>

factories.yml
    logger:
      class: sfAggregateLogger
      param:
        level: debug

**Comment by kevindew** [comment]
thanks for the info, do you know if symfony is throwing the 404 error or if it is thrown by your web server? as it could be (at a guess) that your web server is not sending the requests for .css extensions. Just checking now on one of my dev sites /css-min/key/efd938eb7c4e7deb2c0bae5d6677af7ec9bd48cf/t/1295376145 and css-min/key/efd938eb7c4e7deb2c0bae5d6677af7ec9bd48cf/t/1295376145.css are working urls

**Comment by nibsirahsieu** [comment]
if i look at Apache error log, i got an error like the following: [error] [client 127.0.1.1] File does not exist: /home/webdev/myblog/web/css-min, referer: http://myblog.localhost/.
By the way, I've resolved the issue by overriding the sfCombine routing.yml and add suffix: .html into it. But the link now become http://myblog.localhost/css-min/key/95558ffc86076c12137c00f48350acc0e2bc3b0c/t/1296238009.html.

Thanks for your help

best regards nibsirahsieu

**Comment by kevindew** [comment]
OK great, i think the problem must be at server level. Cheers

**Comment by klemens-u** [comment]
The problem is definitly with "no_script_name".  The solution is to allow .css paths in .htaccess. Add the line with ".css".

```
# we skip all files with .something
RewriteCond %{REQUEST_URI} \..+$
RewriteCond %{REQUEST_URI} !\.html$
RewriteCond %{REQUEST_URI} !\.css$
RewriteRule .* - [L]
```
